@startuml

    class UserManager [[UserManager.html]] {
        +UserManager(List<User>)
        +getAllUsers(): List<User>
        +findUserIndexById(UUID): int
        +findUserByEmail(String): int
        +getUserByIndex(int): User
        +createUser(String, String, String, UserType): void
        +addFriendById(UUID): void
        +removeFriendById(UUID): void
        +getEventList(): List<UUID>
        +registerEventById(UUID): void
        +cancelEventById(UUID): void
        +startConversationById(UUID): void
        +getUserIdByIndex(int): UUID
        +addConversation(UUID, int): void
        +markConversationAsUnread(UUID, int): void
        +markConversationAsRead(UUID): void
        +archiveConversation(UUID, Integer, int): void
        +deleteConversation(UUID, Integer, int): void
        +getArchivedConversationsList(): HashMap<UUID, Integer>
        +getDeletedConversationsList(): HashMap<UUID, Integer>
        +getUnreadConversationList(): List<UUID>
        +getIndexOfActiveUser(): int
        +hasConversation(UUID): boolean
        +getConversations(): List<UUID>
        +getUserName(int): String
        +getFriends(): List<UUID>
        +getEmail(UUID): String
        +isFriend(int): boolean
        +userHasMeAsFriend(int): boolean
        +getActiveUserId(): UUID
        +getActiveUserType(): UserType
        +setUserType(int, UserType): void
        +getIsUserLoggedIn(): boolean
        +isValidUserIndex(int): boolean
        +logout(): void
        +loginAsAGuest(): String
        +checkCredential(String, String): boolean
        +login(String, String): boolean
        +getAllUsersOfType(UserType): List<UUID>
        +displayUsers(List<UUID>): List<String>
        +setName(User, String): void
        +removeEvent(User, UUID): void
        +getAllVipUsers(): HashSet<UUID>
        +interestedInEvent(UUID): boolean
        +uninterestedInEvent(UUID): boolean
        +getInterestedEventsIds(): HashSet<UUID>
        +likeSpeakerById(UUID): boolean
        +dislikeSpeakerById(UUID): boolean
        +getFavouriteSpeakersId(): List<UUID>
        +isFavouriteSpeaker(UUID, UUID): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
